name: idsr      
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.2.5+1
  path_provider: ^2.0.15
  path: ^1.8.3
  csv: ^5.0.0
  excel: ^2.0.4
  cupertino_icons: ^1.0.8   
  fl_chart: ^0.63.0      
  http: ^0.13.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/icon.png"  # <-- Replace this with your icon path

   